name: Build buildroot toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build toolchain
    runs-on: ubuntu-26.04
    steps:
      - name: Install buildroot prerequisites
        run: |
          set -eux
          sudo apt install -y build-essential

      - name: Get buildroot
        run: |
          set -eux
          curl --retry 5 -L "http://buildroot.org/downloads/buildroot-2026.05.3.tar.xz" | tar xf -
